env:
  es6: true
  browser: true
  commonjs: true
  jest: true
extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react', 'eslint-plugin-import']

rules: {
  'import/order': ["error", {
    "alphabetize": {"order": "asc", "caseInsensitive": true},
    "groups": ["builtin", "external", "parent", "sibling", "index"]
  }]
}

settings:
  react:
    version: '16'
